# Generated by Django 5.2.9 on 2025-12-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(choices=[('null', 'null'), ('blank', 'blank'), ('unique', 'unique'), ('primary_key', 'primary_key'), ('db_index', 'db_index'), ('default', 'default'), ('editable', 'editable'), ('choices', 'choices'), ('help_text', 'help_text'), ('verbose_name', 'verbose_name'), ('max_length', 'max_length'), ('unique_for_date', 'unique_for_date'), ('unique_for_month', 'unique_for_month'), ('unique_for_year', 'unique_for_year'), ('auto_now', 'auto_now'), ('auto_now_add', 'auto_now_add'), ('validators', 'validators'), ('error_messages', 'error_messages'), ('db_column', 'db_column'), ('db_tablespace', 'db_tablespace'), ('serialize', 'serialize'), ('on_delete', 'on_delete'), ('related_name', 'related_name'), ('through', 'through'), ('through_fields', 'through_fields'), ('limit_choices_to', 'limit_choices_to'), ('swappable', 'swappable')], max_length=100)),
                ('option_value', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('AutoField', 'AutoField'), ('BigAutoField', 'BigAutoField'), ('BigIntegerField', 'BigIntegerField'), ('BinaryField', 'BinaryField'), ('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('DecimalField', 'DecimalField'), ('DurationField', 'DurationField'), ('EmailField', 'EmailField'), ('FileField', 'FileField'), ('FilePathField', 'FilePathField'), ('FloatField', 'FloatField'), ('ImageField', 'ImageField'), ('IntegerField', 'IntegerField'), ('GenericIPAddressField', 'GenericIPAddressField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('PositiveSmallIntegerField', 'PositiveSmallIntegerField'), ('SlugField', 'SlugField'), ('SmallIntegerField', 'SmallIntegerField'), ('TextField', 'TextField'), ('TimeField', 'TimeField'), ('URLField', 'URLField'), ('UUIDField', 'UUIDField'), ('ForeignKey', 'ForeignKey'), ('OneToOneField', 'OneToOneField'), ('ManyToManyField', 'ManyToManyField')], max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('field_option', models.ManyToManyField(related_name='options', to='documentation.fieldoptions')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_project', models.CharField(max_length=100)),
                ('parent_app', models.CharField(max_length=100)),
                ('module', models.CharField(choices=[('admins', 'admins'), ('apps', 'apps'), ('forms', 'forms'), ('models', 'models'), ('permissions', 'permissions'), ('serializers', 'serializers'), ('utils', 'utils'), ('services', 'services'), ('signals', 'signals'), ('tests', 'tests'), ('views', 'views'), ('urls', 'urls')], max_length=100)),
                ('member_name', models.CharField(max_length=100)),
                ('fields', models.ManyToManyField(related_name='fields', to='documentation.modelfields')),
            ],
        ),
    ]
