# Generated by Django 5.2.9 on 2025-12-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument_name', models.CharField(max_length=100)),
                ('argument_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FieldArgumentPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument_value', models.CharField(max_length=100)),
                ('argument_value_description', models.TextField(default='argument_description')),
                ('field_argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.fieldargument')),
            ],
        ),
        migrations.CreateModel(
            name='ModelDocEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_project', models.CharField(help_text='The name of the django project this item belongs to.', max_length=100)),
                ('parent_app', models.CharField(help_text='The name of the django app this item belongs to.', max_length=100)),
                ('module_type', models.CharField(default='model', help_text='The type of the module(model, view, url) this item belongs to.', max_length=100)),
                ('model_name', models.CharField(help_text='The name of the model being documented.', max_length=100)),
                ('model_description', models.TextField()),
                ('model_fields', models.ManyToManyField(help_text='The fields (CharField, ForeignKey) this model has.', related_name='fields', to='documentation.modelfield')),
            ],
        ),
        migrations.CreateModel(
            name='ModelVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100, unique=True)),
                ('variable_description', models.TextField()),
                ('variable_is_required', models.BooleanField(default=False)),
                ('field_arguments', models.ManyToManyField(related_name='field_arguments', through='documentation.FieldArgumentPair', to='documentation.fieldargument')),
                ('variable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.modelfield')),
            ],
        ),
        migrations.AddField(
            model_name='fieldargumentpair',
            name='model_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.modelvariable'),
        ),
    ]
