# Generated by Django 5.2.9 on 2025-12-12 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldargumentpair',
            old_name='model_field',
            new_name='variable_name',
        ),
        migrations.RenameField(
            model_name='modelvariable',
            old_name='variable_type',
            new_name='model_field',
        ),
        migrations.RemoveField(
            model_name='modeldocentry',
            name='model_fields',
        ),
        migrations.AddField(
            model_name='modelvariable',
            name='model',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='documentation.modeldocentry'),
            preserve_default=False,
        ),
    ]
