# Generated by Django 5.2.9 on 2025-12-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldoptions',
            name='value_description',
            field=models.TextField(default='string'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelfields',
            name='field_description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='modelfields',
            name='field_option',
        ),
        migrations.AddField(
            model_name='modelfields',
            name='field_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='documentation.fieldoptions'),
            preserve_default=False,
        ),
    ]
