# Generated by Django 5.2.8 on 2025-11-30 20:28

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", martor.models.MartorField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="postmeta",
            name="post",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="PostMeta",
        ),
    ]
