# Generated by Django 5.2.9 on 2025-12-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_rename_model_field_fieldargumentpair_variable_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvariable',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
