# Generated by Django 5.2.9 on 2025-12-11 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_fieldoptions_value_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfields',
            name='field_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='documentation.fieldoptions'),
        ),
    ]
