# Generated by Django 5.2.9 on 2025-12-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_alter_modelfields_field_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFieldArgumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument_name', models.CharField(choices=[('null', 'null'), ('blank', 'blank'), ('unique', 'unique'), ('primary_key', 'primary_key'), ('db_index', 'db_index'), ('default', 'default'), ('editable', 'editable'), ('choices', 'choices'), ('help_text', 'help_text'), ('verbose_name', 'verbose_name'), ('max_length', 'max_length'), ('unique_for_date', 'unique_for_date'), ('unique_for_month', 'unique_for_month'), ('unique_for_year', 'unique_for_year'), ('auto_now', 'auto_now'), ('auto_now_add', 'auto_now_add'), ('on_delete', 'on_delete'), ('related_name', 'related_name'), ('through', 'through'), ('through_fields', 'through_fields'), ('limit_choices_to', 'limit_choices_to'), ('swappable', 'swappable')], max_length=100)),
                ('argument_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelFieldTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type_name', models.CharField(choices=[('AutoField', 'AutoField'), ('BigAutoField', 'BigAutoField'), ('BigIntegerField', 'BigIntegerField'), ('BinaryField', 'BinaryField'), ('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('DecimalField', 'DecimalField'), ('DurationField', 'DurationField'), ('EmailField', 'EmailField'), ('FileField', 'FileField'), ('FilePathField', 'FilePathField'), ('FloatField', 'FloatField'), ('ImageField', 'ImageField'), ('IntegerField', 'IntegerField'), ('GenericIPAddressField', 'GenericIPAddressField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('PositiveSmallIntegerField', 'PositiveSmallIntegerField'), ('SlugField', 'SlugField'), ('SmallIntegerField', 'SmallIntegerField'), ('TextField', 'TextField'), ('TimeField', 'TimeField'), ('URLField', 'URLField'), ('UUIDField', 'UUIDField'), ('ForeignKey', 'ForeignKey'), ('OneToOneField', 'OneToOneField'), ('ManyToManyField', 'ManyToManyField')], max_length=100)),
                ('field_type_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='modelfields',
            name='field_option',
        ),
        migrations.CreateModel(
            name='FieldArgumentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field_argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.modelfieldargumentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelFieldsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_field_name', models.CharField(max_length=100, unique=True)),
                ('model_field_description', models.TextField()),
                ('model_field_is_required', models.BooleanField(default=False)),
                ('model_field_arguments', models.ManyToManyField(through='documentation.FieldArgumentMapping', to='documentation.modelfieldargumentmodel')),
                ('model_field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.modelfieldtypesmodel')),
            ],
        ),
        migrations.AddField(
            model_name='fieldargumentmapping',
            name='model_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.modelfieldsmodel'),
        ),
        migrations.CreateModel(
            name='ModelsDocumentationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_project', models.CharField(help_text='The name of the django project this item belongs to.', max_length=100)),
                ('parent_app', models.CharField(help_text='The name of the django app this item belongs to.', max_length=100)),
                ('module_type', models.CharField(default='model', help_text='The type of the module(model, view, url) this item belongs to.', max_length=100)),
                ('model_name', models.CharField(help_text='The name of the model being documented.', max_length=100)),
                ('model_description', models.TextField()),
                ('model_fields', models.ManyToManyField(help_text='The fields (Charfield, ForeignKey) this model has.', related_name='fields', to='documentation.modelfieldsmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentationEntry',
        ),
        migrations.DeleteModel(
            name='FieldOptions',
        ),
        migrations.DeleteModel(
            name='ModelFields',
        ),
    ]
