# Generated by Django 5.2.9 on 2025-12-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_modelvariable_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelvariable',
            name='slug',
        ),
        migrations.AddField(
            model_name='modelvariable',
            name='name_of_parent_model',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
