# Generated by Django 5.2.9 on 2025-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_modelfieldargumentmodel_modelfieldtypesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldargumentmapping',
            name='value_description',
            field=models.TextField(default='blank'),
            preserve_default=False,
        ),
    ]
