# Generated by Django 5.2.9 on 2025-12-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_remove_modelvariable_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvariable',
            name='variable_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='modelvariable',
            unique_together={('model', 'variable_name')},
        ),
    ]
