# Generated by Django 5.2.9 on 2025-12-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_alter_modelvariable_variable_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldargumentpair',
            name='human_readable_name',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
