# Generated by Django 5.2.9 on 2025-12-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_fieldargumentmapping_value_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfieldargumentmodel',
            name='argument_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelfieldtypesmodel',
            name='field_type_name',
            field=models.CharField(max_length=100),
        ),
    ]
