# Generated by Django 5.2.9 on 2025-12-12 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_fieldargumentpair_human_readable_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldargumentpair',
            name='human_readable_name',
        ),
        migrations.AlterField(
            model_name='fieldargumentpair',
            name='variable_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argument_pairs', to='documentation.modelvariable'),
        ),
        migrations.AlterField(
            model_name='modelvariable',
            name='field_arguments',
            field=models.ManyToManyField(related_name='model_variables', through='documentation.FieldArgumentPair', to='documentation.fieldargument'),
        ),
    ]
