# Generated by Django 5.2.9 on 2025-12-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_alter_modelfieldargumentmodel_argument_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldargumentmapping',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
