# Generated by Django 5.2.9 on 2025-12-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeatherModel',
            fields=[
                ('dt', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sunrise', models.BigIntegerField()),
                ('sunset', models.BigIntegerField()),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('dewpoint', models.FloatField()),
                ('uv_index', models.IntegerField()),
                ('clouds', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('wind_deg', models.IntegerField()),
                ('rain', models.IntegerField(blank=True, null=True)),
                ('snow', models.IntegerField(blank=True, null=True)),
                ('weather_id', models.IntegerField()),
                ('weather_main', models.CharField(max_length=120)),
                ('weather_description', models.CharField(max_length=200)),
                ('weather_icon', models.URLField()),
            ],
        ),
    ]
