# Generated by Django 5.2.8 on 2025-11-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentWeatherModel",
            fields=[
                ("dt", models.BigIntegerField(primary_key=True, serialize=False)),
                ("sunrise", models.BigIntegerField()),
                ("sunset", models.BigIntegerField()),
                ("temp", models.IntegerField()),
                ("feels_like", models.IntegerField()),
                ("pressure", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("dewpoint", models.IntegerField()),
                ("clouds", models.IntegerField()),
                ("uv_index", models.IntegerField()),
                ("visibility", models.IntegerField()),
                ("wind_speed", models.IntegerField()),
                ("wind_gust", models.IntegerField()),
                ("wind_deg", models.IntegerField()),
                ("rain", models.IntegerField()),
                ("snow", models.IntegerField()),
                ("weather_id", models.IntegerField()),
                ("weather_main", models.CharField(max_length=120)),
                ("weather_description", models.CharField(max_length=200)),
                ("weather_icon", models.URLField()),
            ],
        ),
    ]
