# Generated by Django 5.2.8 on 2025-11-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentweathermodel",
            name="dewpoint",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="currentweathermodel",
            name="feels_like",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="currentweathermodel",
            name="pressure",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="currentweathermodel",
            name="rain",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="currentweathermodel",
            name="snow",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="currentweathermodel",
            name="temp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="currentweathermodel",
            name="wind_gust",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="currentweathermodel",
            name="wind_speed",
            field=models.FloatField(),
        ),
    ]
